# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml
      - name: Report Test Results
        if: ${{ github.event_name == 'push' }}
        run: mvn -B surefire-report:report-only --file pom.xml
      - name: Upload Test Results
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/site/surefire-report.html
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-summary: true
          fail-on-coverage-decrease: true
      - name: Log coverage percentage(if it changed)
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.json
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badge" *.svg
            git push
          fi
      - name: Upload JaCoCo coverage report
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
